mutation forgotPassword($email: String!) {
  forgotPassword(
    input: {
      email: $email
      reset_password_url: {
        url: "https://perguidex.io/reset?email=__EMAIL__&token=__TOKEN__"
      }
    }
  ) {
    status
    message
  }
}
